AutomatedQuestionPaper/Areas/Staff/Controllers/StaffHomePageController.cs
using System.Linq;
using System.Web.Mvc;
using AutomatedQuestionPaper.Controllers;
using AutomatedQuestionPaper.Models;

namespace AutomatedQuestionPaper.Areas.Staff.Controllers
{
    [SessionCheckStaff]
    public class StaffHomePageController : AlertController
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        [HttpGet]
        public ActionResult Index()
        {
            var staff = (string) Session["Staff_Name"];
            return View(_context.Staffs.FirstOrDefault(m => m.Name == staff));
        }
    }
}

AutomatedQuestionPaper/Areas/Staff/Views/StaffHomePage/Index.cshtml
@model AutomatedQuestionPaper.Models.Staff
@{
	ViewBag.Title = $@"{Model.Name} (Staff) Home Page";
	Layout = "~/Areas/Staff/Views/Shared/_staffLoginLayoutPage.cshtml";
}

@if (TempData["SessionErrorMessage"] != null)
{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";

	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		@TempData["SessionErrorMessage"]
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}
else
{
	ViewBag.Title = $@"{Model.Name} (Staff) Home Page";
	Layout = "~/Areas/Staff/Views/Shared/_staffLoginLayoutPage.cshtml";

	<br/>
	<h2>@Model.Name Management Panel</h2>

	if (Model.Password == "test_test")
	{
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-primary" style="display: none" id="passwordDialog" name="passwordDialog" data-toggle="modal" data-target="#exampleModalCenter">
			Launch demo modal
		</button>


		<!-- Modal -->
		<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					@using (Html.BeginForm("SetPassword", "StaffHomePage", FormMethod.Post))
					{
						<div class="modal-body">
							<label>Please enter password for account</label>
							<input type="password" class="form-control" name="passwordField" id="passwordField" placeholder="password" data-val="true" data-val-required="The password field is required" />
							<span class="field-validation-valid text-danger" data-valmsg-for="passwordField" data-valmsg-replace="true"></span>
						</div>
						<div class="modal-footer">
							<input type="submit" class="btn btn-outline-primary" value="Save changes" />
						</div>
					}
				</div>
			</div>
		</div>
	}




	<div style="text-align: center">
		<div id="questionDiv" class="card" style="float: left; height: 285px; margin: 10px; width: 12rem;">
			<img class="card-img-top" height="180" src="~/Images/question.jpg" alt="Card image cap">
			<div class="card-body">
				<a class="card-title text-primary">Questions management</a>
			</div>
		</div>

		<div id="chapterDiv" class="card" style="float: left; height: 285px; margin: 10px; width: 12rem;">
			<img class="card-img-top" height="180" src="~/Images/chapter.jpg" alt="Card image cap">
			<div class="card-body">
				<a class="card-title text-primary">Chapter management</a>
			</div>
		</div>

		<div id="paperCreationDiv" class="card" style="float: left; height: 285px; margin: 10px; width: 12rem;">
			<img class="card-img-top" height="180" src="~/Images/question paper.jpg" alt="Card image cap">
			<div class="card-body">
				<a class="card-title text-primary">Question Paper creation</a>
			</div>
		</div>

		<div id="paperRepositoryDiv" class="card" style="float: left; height: 285px; margin: 10px; width: 12rem;">
			<img class="card-img-top" height="180" src="~/Images/question paper repository.jpg" alt="Card image cap">
			<div class="card-body">
				<a class="card-title text-primary">Question Paper repository</a>
			</div>
		</div>
	</div>
}


@section Scripts
{
	@Scripts.Render("~/bundles/jqueryval")

	<script>

		$("#passwordDialog").click();

		$(function() {
			$(".card").css('transition', '0.2s');

			$(".card").hover(
				function() {
					$(this).addClass('shadow-lg').css('cursor', 'pointer');
				},
				function() {
					$(this).removeClass('shadow-lg');
				}
			);

			$("a.card-title.text-primary").hover(function () {
				$(this).toggleClass("text-primary text-danger");
			});

			$("#questionDiv").click(function() {
				window.location.href = "@Url.Action("Index", "Question")";
			});

			$("#chapterDiv").click(function() {
				window.location.href = "@Url.Action("Index", "Chapter")";
			});

			$("#paperCreationDiv").click(function() {
				window.location.href = "@Url.Action("Index", "PaperCreation")";
			});

			$("#paperRepositoryDiv").click(function() {
				window.location.href = "@Url.Action("Index", "QuestionPaperRepository")";
			});
		});
	</script>
}

AutomatedQuestionPaper/Areas/Staff/Views/StaffHomePage/StaffHomePage.cshtml
@{
    ViewBag.Title = "StaffHomePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Staff Home Page</h2>