AutomatedQuestionPaper/Areas/Staff/Controllers/ParagraphQuestionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using AutomatedQuestionPaper.Controllers;
using AutomatedQuestionPaper.Areas.Staff.Models;
using AutomatedQuestionPaper.Models;

namespace AutomatedQuestionPaper.Areas.Staff.Controllers
{
    public class ParagraphQuestionController : AlertController
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NextStep(string selectedSemester, string selectedDepartment, string selectedSubject, string examType, string chapterName, string unitNo)
        {
            TempData["Para_Semester"] = selectedSemester;
            TempData["Para_Department"] = selectedDepartment;
            TempData["Para_Subject"] = selectedSubject;
            TempData["Para_Chapter"] = chapterName;
            TempData["Para_Unit"] = unitNo;
            TempData["Para_ExamType"] = examType;

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetParagraph()
        {
            return View();
        }

        public ActionResult GenerateQuestion(string paragraphContent)
        {
            var data = GetQuestions(paragraphContent);

            return PartialView("ParagraphGeneratedQuestionList", data);
        }

        public List<string> GetQuestions(string content)
        {
            const string directory = @"C:\Paragraph-question-generator";

            System.IO.File.WriteAllText(@"C:\Paragraph-question-generator\file.txt", content);
            var proc = new Process
            {
                StartInfo =
                {
                    WorkingDirectory = directory,
                    UseShellExecute = false,
                    FileName = @"C:\Paragraph-question-generator\q.bat",
                    WindowStyle = ProcessWindowStyle.Hidden,
                    CreateNoWindow = true
                }
            };
            proc.Start();
            proc.WaitForExit();
            proc.Close();
            proc.Dispose();

            var generatedQuestionList = System.IO.File.ReadLines(@"C:\Paragraph-question-generator\output.txt").ToList();
            System.IO.File.WriteAllText(@"C:\Paragraph-question-generator\output.txt", string.Empty);
            return generatedQuestionList;
        }

        [HttpPost]
        public ActionResult AddQuestion(string[] selectedQuestions, int[] selectedLevel)
        {
            var semester = (string)TempData["Para_Semester"];
            var department = (string)TempData["Para_Department"];
            var subject = (string)TempData["Para_Subject"];
            var chapter = (string)TempData["Para_Chapter"];
            var unit = (string)TempData["Para_Unit"];
            var type = (string)TempData["Para_ExamType"];


            List<int> level = selectedLevel.Where(item => item != 0).ToList();

            for (var i = 0; i < selectedQuestions.Length; i++)
            {
                var newQuestion = new Question
                {
                    UnitId = Convert.ToInt32(unit),
                    SemesterId = Convert.ToString(DatabaseData.GetSemesterInfo(semester).Id),
                    ChapterId = _context.Chapters.FirstOrDefault(k => k.ChapterName == chapter)?.Id,
                    CourseId = DatabaseData.GetCourseInfo(subject).Courseid,
                    DepartmentId = Convert.ToString(DatabaseData.GetDepartmentInfo(department).Id),
                    DifficultyLevel = Convert.ToInt32(level[i]),
                    QuestionText = selectedQuestions[i],
                    QuestionType = (int)Enum.Parse(typeof(ExamType), type),
                    Answers = null
                };

                _context.Questions.Add(newQuestion);
            }

            _context.SaveChanges();

            Alert("Success", "Question added successfully", Enums.NotificationType.success);

            return View("Index");
        }
    }
}

AutomatedQuestionPaper/Areas/Staff/Views/ParagraphQuestion/GetParagraph.cshtml
@{
    ViewBag.Title = "GetParagraph";
    Layout = "~/Areas/Staff/Views/Shared/_staffLoginNavigation.cshtml";
}

<br/>
<h4>Paragraph text : </h4>
<br/>

<form onsubmit="return false">
    <div class="form-group">
        <textarea class="form-control" style="min-height: 200px" name="ParagraphText" id="ParagraphText" required></textarea>
        
        
        <br/>
        <button class="btn btn-outline-success btn-block" name="ParagraphSubmit" id="ParagraphSubmit">Generate</button>
    </div>
</form>

<br/>

<h3>Generated questions : </h3>
<div id="QuestionList" name="QuestionList">

</div>


@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function() {
            $("#ParagraphSubmit").click(function(e) {

                e.preventDefault();
                var paragraphText = $("#ParagraphText").val();
                console.log(paragraphText);
                if (paragraphText !== '') {
                    $.ajax({
                        type: 'Post',
                        url: '@Url.Action("GenerateQuestion", "ParagraphQuestion")',
                        dataType: 'html',
                        data: {
                            paragraphContent: paragraphText
                        },
                        success: function(data) {
                            e.preventDefault();
                            $("#QuestionList").html(data);
                        },
                        error: function(err) {
                            e.preventDefault();
                            $("#QuestionList").html(err);
                        }
                    });
                } else {
                    alert("Please select all the fields");
                }


            });
        });
    </script>
}

AutomatedQuestionPaper/Areas/Staff/Views/ParagraphQuestion/Index.cshtml
@{

    ViewBag.Title = "File upload";
    Layout = "~/Areas/Staff/Views/Shared/_staffLoginNavigation.cshtml";
}

<br />
@if (TempData["QuestionAddedSuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["QuestionAddedSuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<h3>Paragraph Question extractor</h3>

<form>
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Semester</label>
            <select id="selectedSemester" name="selectedSemester" class="form-control" data-val="true" data-val-required="The semester field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSemester" data-valmsg-replace="true"></span>
        </div>

        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Department</label>
            <select id="selectedDepartment" name="selectedDepartment" class="form-control" data-val="true" data-val-required="The department field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedDepartment" data-valmsg-replace="true"></span>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Subject</label>
            <select id="selectedSubject" name="selectedSubject" class="form-control" data-val="true" data-val-required="The subject field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSubject" data-valmsg-replace="true"></span>
        </div>

        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Unit no</label>
            <select id="selectedUnit" name="selectedUnit" class="form-control" data-val="true" data-val-required="The unit field is required">
                <option selected disabled>---Select---</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedUnit" data-valmsg-replace="true"></span>
        </div>

    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">ExamType</label>
            <select id="ExamType" name="ExamType" class="form-control" data-val="true" data-val-required="The ExamType field is required">
                <option selected disabled>---Select---</option>
                <option>InSem</option>
                <option>EndSem</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="ExamType" data-valmsg-replace="true"></span>
        </div>

        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Chapter name</label>
            <select id="chapterName" name="chapterName" class="form-control" data-val="true" data-val-required="The chapter name field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="chapterName" data-valmsg-replace="true"></span>
        </div>
    </div>
    

    <br/>
    <div class="row">
        <div class="col">
            <input type="submit" value="Submit" class="form-control btn btn-primary" id="QuestionSubmitButton" name="QuestionSubmitButton" />
        </div>
    </div>

</form>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function() {

            $("#selectedDepartment").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);
            $("#selectedUnit").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);

            $.ajax({
                url: '@Url.Action("GetAllocatedSemesters", "Chapter")',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    $("#selectedSemester").empty();
                    $("#selectedSemester").append("<option selected disabled>---Select---</option>");
                    for (var i = 0; i < data.length; i++) {
                        $("#selectedSemester").append("<option>" + data[i] + "</option>");
                    }

                    $("#selectedSemester").prop("disabled", false);
                    $("#selectedDepartment").prop("disabled", false);

                },
                error: function(xhr, thrownError) {
                    alert("Something went wrong. \nProblem description -  Error code " +
                        xhr.status +
                        "Message" +
                        thrownError +
                        "");
                }
            });


            $("#selectedSemester").change(function() {
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetAllocatedDepartments", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semesterName: sem
                    },

                    success: function(data) {
                        $("#selectedDepartment").empty();
                        $("#selectedDepartment").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedDepartment").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedDepartment").prop("disabled", false);
                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", true);
                        $("#selectedUnit").prop("selectedIndex", 0);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedDepartment").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetSubjectsList", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        departmentName: dept,
                        semesterName: sem
                    },
                    success: function(data) {
                        $("#selectedSubject").empty();
                        $("#selectedSubject").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedSubject").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedUnit").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                var sub = $("#selectedSubject option:selected").val();
                var unit = $("#selectedUnit option:selected").val();

                $.ajax({
                    url: '@Url.Action("GetChapterList", "ManualType")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semester: sem,
                        department: dept,
                        subject: sub,
                        unit: unit
                    },

                    success: function(data) {
                        $("#chapterName").empty();
                        $("#chapterName").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#chapterName").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#QuestionSubmitButton").click(function(e) {

                e.preventDefault();
                var semester = $("#selectedSemester option:selected").text();
                var department = $("#selectedDepartment option:selected").text();
                var subject = $("#selectedSubject option:selected").text();
                var unit = $("#selectedUnit  option:selected").text();
                var chapterName = $("#chapterName option:selected").text();
                var type = $("#ExamType option:selected").text();
                if (unit !== "---Select---") {
                    $.ajax({
                        type: 'Post',
                        url: '@Url.Action("NextStep", "ParagraphQuestion")',
                        dataType: 'html',
                        data: {
                            selectedSemester: semester,
                            selectedDepartment: department,
                            selectedSubject: subject,
                            unitNo: unit,
                            chapterName: chapterName,
                            examType: type
                        },
                        success: function(data) {
                            window.location.href = '@Url.Action("GetParagraph","ParagraphQuestion")'; //Will take you to Google.
                        },
                        error: function(err) {
                            e.preventDefault();
                            $("#questionList").html(data);
                        }
                    });
                } else {
                    alert("Please select all the fields");
                }


            });


        });
    </script>
}

AutomatedQuestionPaper/Areas/Staff/Views/ParagraphQuestion/ParagraphGeneratedQuestionList.cshtml
@model List<string>

@if (Model != null)
{
    using (Html.BeginForm("AddQuestion", "ParagraphQuestion"))
    {
        <table class="table table-bordered table-responsive table-hover table-striped">
            <tr>
                <th>

                </th>
                <th>
                    Questions
                </th>
                <th>
                    Difficulty Level
                </th>
            </tr>
            <tbody>
                @foreach (var data in Model)
                {
                    <tr>
                        <td style="border: 1px solid black">
                            <input type="checkbox" name="selectedQuestions" id="selectedQuestions" value="@data" />
                        </td>

                        <td style="border: 1px solid black">
                            @data
                        </td>
                        <td style="border: 1px solid black">
                            <select id="selectedLevel" name="selectedLevel">
                                <option>0</option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                            </select>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="form-group text-center">
            <input type="submit" class="btn btn-primary" value="Add questions" />
        </div>
    }
}