AutomatedQuestionPaper/Areas/Staff/Controllers/FileUploadController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedQuestionPaper.Areas.Staff.Models;
using AutomatedQuestionPaper.Controllers;
using AutomatedQuestionPaper.Models;

namespace AutomatedQuestionPaper.Areas.Staff.Controllers
{
    [SessionCheckStaff]
    public class FileUploadController : AlertController
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: Staff/FileUpload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult QuestionFileUpload(string selectedFileType, HttpPostedFileBase fileControl,
            string selectedSemester, string selectedDepartment, string selectedSubject, string selectedUnit,
            string ExamType, string chapterName)
        {
            var extension = Path.GetExtension(fileControl.FileName);

            var subjectId = _context.Courses.FirstOrDefault(u => u.CourseName == selectedSubject)?.Courseid;

            var departmentId = DatabaseData.GetDepartmentInfo(selectedDepartment)?.Id;

            var semesterId = DatabaseData.GetSemesterInfo(selectedSemester)?.Id;

            var unit = Convert.ToInt32(selectedUnit);

            var type = (int) Enum.Parse(typeof(ExamType), ExamType);

            var chapterId = _context.Chapters.FirstOrDefault(x =>
                x.SemesterId == semesterId && x.DepartmentId == departmentId && x.CourseId == subjectId &&
                x.UnitNo == unit && x.ChapterName == chapterName)?.Id;

            // Word file
            if (extension == ".docx" || extension == ".doc")
            {
                ProcessFile.WordFile(fileControl);
            }

            // CSV file
            else if (extension == ".csv" || extension == ".CSV")
            {
                var data = ProcessFile.CsvFile(fileControl);
                if (data.questions == null)
                {
                    TempData["UploadError"] = data.error;
                    return View("Index");
                }

                foreach (var q in data.questions)
                    _context.Questions.Add(new Question
                    {
                        ChapterId = chapterId,
                        CourseId = subjectId,
                        DepartmentId = Convert.ToString(departmentId),
                        DifficultyLevel = q.Level,
                        QuestionText = q.Question,
                        QuestionType = type,
                        SemesterId = Convert.ToString(semesterId),
                        UnitId = unit
                    });
                _context.SaveChangesAsync();

                Alert("Success", "Question set added successfully", Enums.NotificationType.success);

                return RedirectToAction("Index", "Question");
            }
            return null;
        }
    }
}

AutomatedQuestionPaper/Areas/Staff/Views/FileUpload/Index.cshtml
@{

    ViewBag.Title = "File upload";
    Layout = "~/Areas/Staff/Views/Shared/_staffLoginNavigation.cshtml";
}

<br />
@if (TempData["UploadError"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["UploadError"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}


@using (Html.BeginForm("QuestionFileUpload", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Select file</label>
            <input type="file" id="fileControl" name="fileControl" class="form-control-file" required="required" />
            <span class="field-validation-valid text-danger" data-valmsg-for="fileControl" data-valmsg-replace="true"></span>
        </div>

        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">File type</label>
            <select id="selectedFileType" name="selectedFileType" class="form-control" data-val="true" data-val-required="The file type field is required" required>
                <option selected disabled>---Select---</option>
                <option>CSV (.csv)</option>
                <option>Word file (.docx)</option>
            </select>
            <small id="fileHelp" name="fileHelp" class="form-text text-muted">Don't worry if possible we will automatically select the type of file you uploaded.</small>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedFileType" data-valmsg-replace="true"></span>
        </div>


    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Semester</label>
            <select id="selectedSemester" name="selectedSemester" class="form-control" data-val="true" data-val-required="The semester field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSemester" data-valmsg-replace="true"></span>

        </div>
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Department</label>
            <select id="selectedDepartment" name="selectedDepartment" class="form-control" data-val="true" data-val-required="The department field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedDepartment" data-valmsg-replace="true"></span>

        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Subject</label>
            <select id="selectedSubject" name="selectedSubject" class="form-control" data-val="true" data-val-required="The subject field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSubject" data-valmsg-replace="true"></span>

        </div>
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Unit no</label>
            <select id="selectedUnit" name="selectedUnit" class="form-control" data-val="true" data-val-required="The unit field is required">
                <option selected disabled>---Select---</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedUnit" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">ExamType</label>
            <select id="ExamType" name="ExamType" class="form-control" data-val="true" data-val-required="The ExamType field is required">
                <option selected disabled>---Select---</option>
                <option>InSem</option>
                <option>EndSem</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="ExamType" data-valmsg-replace="true"></span>

        </div>
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Chapter name</label>
            <select id="chapterName" name="chapterName" class="form-control" data-val="true" data-val-required="The chapter name field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="chapterName" data-valmsg-replace="true"></span>

        </div>
    </div>

    <br/>

    <div class="row">
        <div class="col">
            <input type="submit" value="Submit" class="form-control btn btn-outline-primary" id="ChapterFormSubmit" name="ChapterFormSubmit" />
        </div>

    </div>
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function() {

            $("#selectedDepartment").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);
            $("#selectedUnit").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);

            $.ajax({
                url: '@Url.Action("GetAllocatedSemesters", "Chapter")',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    $("#selectedSemester").empty();
                    $("#selectedSemester").append("<option selected disabled>---Select---</option>");
                    for (var i = 0; i < data.length; i++) {
                        $("#selectedSemester").append("<option>" + data[i] + "</option>");
                    }

                    $("#selectedSemester").prop("disabled", false);
                    $("#selectedDepartment").prop("disabled", false);

                },
                error: function(xhr, thrownError) {
                    alert("Something went wrong. \nProblem description -  Error code " +
                        xhr.status +
                        "Message" +
                        thrownError +
                        "");
                }
            });


            $("#selectedSemester").change(function() {
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetAllocatedDepartments", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semesterName: sem
                    },

                    success: function(data) {
                        $("#selectedDepartment").empty();
                        $("#selectedDepartment").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedDepartment").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedDepartment").prop("disabled", false);
                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", true);
                        $("#selectedUnit").prop("selectedIndex", 0);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedDepartment").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetSubjectsList", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        departmentName: dept,
                        semesterName: sem
                    },
                    success: function(data) {
                        $("#selectedSubject").empty();
                        $("#selectedSubject").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedSubject").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedUnit").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                var sub = $("#selectedSubject option:selected").val();
                var unit = $("#selectedUnit option:selected").val();

                $.ajax({
                    url: '@Url.Action("GetChapterList", "ManualType")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semester: sem,
                        department: dept,
                        subject: sub,
                        unit: unit
                    },

                    success: function(data) {
                        $("#chapterName").empty();
                        $("#chapterName").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#chapterName").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }
                });
            });

            $("#fileControl").change(function() {
                var selectedFile = $(this).val();
                var extension = selectedFile.split('.').pop();

                if (extension == 'csv' || extension == 'CSV') {
                    $("#selectedFileType").val("CSV (.csv)");
                    $("#fileHelp").text("We automatically selected the type of file you uploaded");
                    return;

                }

                if (extension == 'docx' || extension == 'DOCX') {
                    $("#selectedFileType").val("Word file (.docx)");
                    $("#fileHelp").text("We automatically selected the type of file you uploaded");
                    return;
                }

                $("#selectedFileType").val("---Select---");
                $("#fileHelp").text("We failed to select type. Please make sure you selected the right type");
            });
        });
    </script>
}