AutomatedQuestionPaper/Areas/Staff/Controllers/ManualTypeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutomatedQuestionPaper.Areas.Staff.Models;
using AutomatedQuestionPaper.Models;
using System.Collections.Generic;
using System.Net;
using Newtonsoft.Json;
using AutomatedQuestionPaper.Controllers;

namespace AutomatedQuestionPaper.Areas.Staff.Controllers
{
    [SessionCheckStaff]
    public class ManualTypeController : AlertController
    {
        private readonly DatabaseContext _context = new DatabaseContext();

        // GET: Staff/ManualType
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddQuestion(string selectedSemester, string selectedDepartment, string selectedSubject,
            string selectedUnit, string chapterName, string question, string ExamType, string difficultyLevel)
        {
            // Get the semester Id
            var semesterId = DatabaseData.GetSemesterInfo(selectedSemester).Id;

            // Get the department Id
            var departmentId = DatabaseData.GetDepartmentInfo(selectedDepartment).Id;

            var subjectId = DatabaseData.GetCourseInfo(selectedSubject).Courseid;

            var unitInt = Convert.ToInt32(selectedUnit);

            var chapterId = _context.Chapters.FirstOrDefault(x =>
                x.SemesterId == semesterId && x.DepartmentId == departmentId && x.CourseId == subjectId &&
                x.UnitNo == unitInt && x.ChapterName == chapterName)?.Id;

            var type = (int)Enum.Parse(typeof(ExamType), ExamType);

            TempData["dept"] = departmentId;
            TempData["sem"] = semesterId;
            TempData["sub"] = subjectId;
            TempData["unit"] = unitInt;
            TempData["chapter"] = chapterId;
            TempData["exam"] = type;
            TempData["difflevel"] = difficultyLevel;

            var questionsList = _context.Questions.Where(x => x.SemesterId == semesterId.ToString()
                                                              && x.DepartmentId == departmentId.ToString()
                                                              && x.CourseId == subjectId
                                                              && x.UnitId == unitInt
                                                              && x.ChapterId == chapterId
                                                              && x.QuestionType == type)
                                                              .Select(x => x.QuestionText)
                .ToList();


            var url = "http://127.0.0.1:5000/semantic";

            var serverOutputDataList = new List<ServerOutputData>();

            
            if (questionsList.Count != 0)
            {
                foreach (var que in questionsList)
                {
                    var data = new
                    {
                        first_text = question,
                        second_text = que
                    };

                    var cli = new WebClient
                    {
                        Headers = {[HttpRequestHeader.ContentType] = "application/json"}
                    };
                    var response = cli.UploadString(url, JsonConvert.SerializeObject(data));
                    var output = JsonConvert.DeserializeObject<ServerOutputData>(response);
                    serverOutputDataList.Add(output);
                }

                var highestSemanticScore = serverOutputDataList.OrderByDescending(i => i.SemanticScore).First();

                if (highestSemanticScore.SemanticScore > 0.75)
                {
                    TempData["oldquestion"] = highestSemanticScore.FirstText;
                    return RedirectToAction("Semantic", highestSemanticScore);
                }
                else
                {
                    _context.Questions.Add(new Question
                    {
                        ChapterId = chapterId,
                        CourseId = subjectId,
                        DepartmentId = departmentId.ToString(),
                        DifficultyLevel = Convert.ToInt32(difficultyLevel),
                        QuestionText = question,
                        QuestionType = type,
                        SemesterId = semesterId.ToString(),
                        UnitId = unitInt
                    });

                    _context.SaveChanges();
                }
            }
            else
            {
                _context.Questions.Add(new Question
                {
                    ChapterId = chapterId,
                    CourseId = subjectId,
                    DepartmentId = departmentId.ToString(),
                    DifficultyLevel = Convert.ToInt32(difficultyLevel),
                    QuestionText = question,
                    QuestionType = type,
                    SemesterId = semesterId.ToString(),
                    UnitId = unitInt
                });

                _context.SaveChangesAsync();
            }
            
            Alert("Success", "Question added successfully", Enums.NotificationType.success);
            return View("Index");
        }

        [HttpPost]
        public ActionResult AddSemanticSimilarQuestion(string newQuestionText, string difficultyLevel)
        {
            if (newQuestionText == null)
            {
                newQuestionText = (string) TempData["oldquestion"];
            }

            if (difficultyLevel == null)
            {
                difficultyLevel = (string) TempData["difflevel"];
            }

            var departmentId = (int) TempData["dept"];
            var semesterId = (int) TempData["sem"];
            var subjectId = (int) TempData["sub"];
            var unitInt = (int) TempData["unit"];
            var chapterId = (int) TempData["chapter"];
            var type = (int) TempData["exam"];

            _context.Questions.Add(new Question
            {
                ChapterId = chapterId,
                CourseId = subjectId,
                DepartmentId = departmentId.ToString(),
                DifficultyLevel = Convert.ToInt32(difficultyLevel),
                QuestionText = newQuestionText,
                QuestionType = type,
                SemesterId = semesterId.ToString(),
                UnitId = unitInt
            });


            _context.SaveChanges();

            Alert("Success", "Question added successfully", Enums.NotificationType.success);

            return View("Index");
        }

        public ActionResult Semantic(ServerOutputData data)
        {
            return View("SemanticSimilar",data);
        }

        public ActionResult GetChapterList(string semester, string department, string subject, string unit)
        {
            var semesterId = DatabaseData.GetSemesterInfo(semester)?.Id;

            var departmentId = DatabaseData.GetDepartmentInfo(department)?.Id;

            var subjectId = DatabaseData.GetCourseInfo(subject)?.Courseid;

            var unitInt = Convert.ToInt32(unit);

            var chapters = _context.Chapters
                .Where(x => x.SemesterId == semesterId && x.DepartmentId == departmentId && x.CourseId == subjectId &&
                            x.UnitNo == unitInt).Select(x => x.ChapterName).ToList();

            return Json(chapters, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditQuestionDetails(string question, string level, string semester, string department,
            string chapter, string type, string unit)
        {
            var levelInt = Convert.ToInt32(level);
            var chap = Convert.ToInt32(chapter);
            var quesType = Convert.ToInt32(type);
            var unitNo = Convert.ToInt32(unit);
            var ques = _context.Questions.FirstOrDefault(t =>
                t.QuestionText == question &&
                t.DifficultyLevel == levelInt &&
                t.SemesterId == semester &&
                t.DepartmentId == department &&
                t.ChapterId == chap &&
                t.QuestionType == quesType &&
                t.UnitId == unitNo
            );
            var sem = Convert.ToInt32(ques.SemesterId);
            var dep = Convert.ToInt32(ques.DepartmentId);

            TempData["Semester-Name"] = _context.Semesters.FirstOrDefault(x => x.Id == sem)?.SemesterName;
            TempData["Department-Name"] = _context.Departments.FirstOrDefault(x => x.Id == dep)?.DepartmentName;
            TempData["Subject-Name"] = _context.Courses.FirstOrDefault(x => x.Courseid == ques.CourseId)?.CourseName;
            TempData["Chapter-Name"] = _context.Chapters.FirstOrDefault(x => x.Id == ques.ChapterId)?.ChapterName;
            TempData["Level"] = level;

            if (ques.QuestionType == 0)
                TempData["Type-Name"] = "InSem";
            else if (ques.QuestionType == 1) TempData["Type-Name"] = "EndSem";

            // TODO lot of work has to be done in view. start with fetching allocated subject list


            return View(ques);
        }

        [HttpPost]
        public ActionResult EditQuestionDetails(string selectedSemester, string selectedDepartment,
            string selectedSubject, string selectedUnit, string chapterName, string question, int? QuestionHiddenId,
            string difficultyLevel, string ExamType)
        {
            var num = Convert.ToInt32(Request.Form["Id"]);

            var dbQuestion = _context.Questions.FirstOrDefault(x => x.Id == num);

            // Get the semester Id
            var semesterId = _context.Semesters.FirstOrDefault(x => x.SemesterName == selectedSemester)?.Id;

            // Get the department Id
            var departmentId = _context.Departments.FirstOrDefault(x => x.DepartmentName == selectedDepartment)?.Id;

            var subjectId = _context.Courses.FirstOrDefault(x => x.CourseName == selectedSubject)?.Courseid;

            var unitNo = Convert.ToInt32(selectedUnit);

AutomatedQuestionPaper/Areas/Staff/Views/ManualType/Index.cshtml
@model List<string>
@{
    ViewBag.Title = "Add question manually";
    Layout = "~/Areas/Staff/Views/Shared/_staffLoginNavigation.cshtml";
}
<br/>

@using (Html.BeginForm("AddQuestion", "ManualType", FormMethod.Post))
{
    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Semester</label>
            <select id="selectedSemester" name="selectedSemester" class="form-control" data-val="true" data-val-required="The semester field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSemester" data-valmsg-replace="true"></span>
        </div>
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Department</label>
            <select id="selectedDepartment" name="selectedDepartment" class="form-control" data-val="true" data-val-required="The department field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedDepartment" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Subject</label>
            <select id="selectedSubject" name="selectedSubject" class="form-control" data-val="true" data-val-required="The subject field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedSubject" data-valmsg-replace="true"></span>
        </div>

        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Unit no</label>
            <select id="selectedUnit" name="selectedUnit" class="form-control" data-val="true" data-val-required="The unit field is required">
                <option selected disabled>---Select---</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="selectedUnit" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">ExamType</label>
            <select id="ExamType" name="ExamType" class="form-control" data-val="true" data-val-required="The ExamType field is required">
                <option selected disabled>---Select---</option>
                <option>InSem</option>
                <option>EndSem</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="ExamType" data-valmsg-replace="true"></span>
        </div>
        <div class="col-sm-12 col-lg-6">
            <label class="col-form-label">Chapter name</label>
            <select id="chapterName" name="chapterName" class="form-control" data-val="true" data-val-required="The chapter name field is required"></select>
            <span class="field-validation-valid text-danger" data-valmsg-for="chapterName" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label class="col-form-label">Question</label>
            <textarea name="question" id="question" class="form-control" data-val="true" data-val-required="The question is required" required></textarea>
            <span class="field-validation-valid text-danger" data-valmsg-for="question" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label class="col-form-label">Difficulty level</label>
            <select id="difficultyLevel" name="difficultyLevel" class="form-control" data-val="true" data-val-required="The difficulty level field is required">
                <option selected disabled>---Select---</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
            </select>
            <span class="field-validation-valid text-danger" data-valmsg-for="difficultyLevel" data-valmsg-replace="true"></span>
        </div>
    </div>

    <br/>
    <div class="form-group">
        <input type="submit" value="Submit" class="form-control btn btn-primary" id="ChapterFormSubmit" name="ChapterFormSubmit"/>
    </div>
}

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function() {

            $("#selectedDepartment").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);
            $("#selectedUnit").prop("disabled", true);
            $("#selectedSubject").prop("disabled", true);

            $.ajax({
                url: '@Url.Action("GetAllocatedSemesters", "Chapter")',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    $("#selectedSemester").empty();
                    $("#selectedSemester").append("<option selected disabled>---Select---</option>");
                    for (var i = 0; i < data.length; i++) {
                        $("#selectedSemester").append("<option>" + data[i] + "</option>");
                    }

                    $("#selectedSemester").prop("disabled", false);
                    $("#selectedDepartment").prop("disabled", false);

                },
                error: function(xhr, thrownError) {
                    alert("Something went wrong. \nProblem description -  Error code " +
                        xhr.status +
                        "Message" +
                        thrownError +
                        "");
                }
            });


            $("#selectedSemester").change(function() {
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetAllocatedDepartments", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semesterName: sem
                    },

                    success: function(data) {
                        $("#selectedDepartment").empty();
                        $("#selectedDepartment").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedDepartment").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedDepartment").prop("disabled", false);
                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", true);
                        $("#selectedUnit").prop("selectedIndex", 0);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedDepartment").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                $.ajax({
                    url: '@Url.Action("GetSubjectsList", "Chapter")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        departmentName: dept,
                        semesterName: sem
                    },
                    success: function(data) {
                        $("#selectedSubject").empty();
                        $("#selectedSubject").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#selectedSubject").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });

            $("#selectedUnit").change(function() {
                var dept = $("#selectedDepartment option:selected").val();
                var sem = $("#selectedSemester option:selected").val();
                var sub = $("#selectedSubject option:selected").val();
                var unit = $("#selectedUnit option:selected").val();

                $.ajax({
                    url: '@Url.Action("GetChapterList", "ManualType")',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        semester: sem,
                        department: dept,
                        subject: sub,
                        unit: unit
                    },

                    success: function(data) {
                        $("#chapterName").empty();
                        $("#chapterName").append("<option selected disabled>---Select---</option>");
                        for (var i = 0; i < data.length; i++) {
                            $("#chapterName").append("<option>" + data[i] + "</option>");
                        }

                        $("#selectedSubject").prop("disabled", false);
                        $("#selectedUnit").prop("disabled", false);
                    },
                    error: function(xhr, thrownError) {
                        alert("Something went wrong. \nProblem description -  Error code " +
                            xhr.status +
                            "Message" +
                            thrownError +
                            "");
                    }

                });
            });
        });
    </script>
}

AutomatedQuestionPaper/Areas/Staff/Views/ManualType/QuestionList.cshtml
@model List<AutomatedQuestionPaper.Areas.Staff.Models.QuestionFormat>

@if (Model != null)
{
    <table class="table table-bordered table-responsive table-hover" style="width: 100%">
        <tr>
            <th>
                Questions
            </th>
            <th>
                Difficulty Level
            </th>
            <th>
                Action
            </th>
        </tr>
        <tbody>
            @foreach (var data in Model)
            {
                <tr>
                    <td style="border: 1px solid black">
                        @data.Question
                    </td>
                    <td style="border: 1px solid black">
                        @data.Level
                    </td>
                    <td style="border: 1px solid black">
                        @Html.ActionLink("Edit", "EditQuestionDetails",
                            new
                            {
                                question = data.Question,
                                level = data.Level,
                                semester = data.Semester,
                                department = data.Department,
                                chapter = data.Chapter,
                                type = data.QuestionType,
                                unit = data.UnitId
                            }
                            , new {@class = "btn btn-outline-danger", id = "QuestionEditButton", name = "QuestionEditButton", data_question = data})
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

AutomatedQuestionPaper/Areas/Staff/Views/ManualType/SemanticSimilar.cshtml
@model AutomatedQuestionPaper.Areas.Staff.Models.ServerOutputData

@{

	ViewBag.Title = "Similar question";
	Layout = "~/Areas/Staff/Views/Shared/_staffLoginNavigation.cshtml";
}

<button type="button" class="btn btn-primary" id="showButton" name="showButton" data-toggle="modal" data-target=".bd-example-modal-lg">Large modal</button>

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Similar question found</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col">
							We found a similar meaning question in repository which matches to the question that you are
							trying to add.
						</div>
					</div>

					<div class="row">
						<div class="col">
							<b>Question details are as follows</b>
						</div>
					</div>
					<div style="margin-top: 10px;"></div>
					<div class="row">
						<div class="col">
							<table class="table table-primary">
								<tbody>
									<tr>
										<th style="width: 190px">Question in repository</th>
										<td>@Model.SecondText</td>
									</tr>
									<tr>
										<th>Your question</th>
										<td>@Model.FirstText</td>

									</tr>
									<tr>
										<th>Similarity score</th>
										<td>@Model.SemanticScore</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
			<div class="modal-footer">
				@using (Html.BeginForm("AddSemanticSimilarQuestion","ManualType",FormMethod.Post))
				{
					<input type="submit" class="btn btn-secondary" value="Still, i want to add it"/>
				}
				
				<button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target=".newQuestionmodal">Edit current question</button>
			</div>
		</div>
	</div>
</div>


<div class="modal fade newQuestionmodal" id="newModal" name="newModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Similar question found</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<label class="col-form-label">Edit current question</label>
				@using (Html.BeginForm("AddSemanticSimilarQuestion", "ManualType", FormMethod.Post))
				{
					<div class="form-group">
						<input type="text" data-val="true" id="newQuestionText" name="newQuestionText" data-val-required="The semester field is required" placeholder="Older question - @Model.FirstText" class="form-control"/>
						<span class="field-validation-valid text-danger" data-valmsg-for="newQuestionText" data-valmsg-replace="true"></span>
					</div>
					<label class="col-form-label">Difficulty level</label>
					<select id="difficultyLevel" name="difficultyLevel" class="form-control" data-val="true" data-val-required="The difficulty level field is required">
						<option selected disabled>---Select---</option>
						<option>1</option>
						<option>2</option>
						<option>3</option>
						<option>4</option>
						<option>5</option>
						<option>6</option>
						<option>7</option>
						<option>8</option>
						<option>9</option>
						<option>10</option>
					</select>
					<span class="field-validation-valid text-danger" data-valmsg-for="difficultyLevel" data-valmsg-replace="true"></span>
					<br />
					<input type="submit" id="submitButton" name="submitButton" class="btn btn-secondary float-left btn-block" value="Submit">
				}
			</div>
			<div class="modal-footer">
			</div>
		</div>
	</div>
</div>



@section scripts
{
	@Scripts.Render("~/bundles/jqueryval")
	<script>
		$(function () {

			$("#showButton").click();


		});
	</script>
}